### ISSUE TITLE
使用后打包报错RollupError: node_modules/react/cjs/react-jsx-runtime.production.min.js (12:7): "default" is not exported by "react?commonjs-external", imported by "node_modules/react/cjs/react-jsx-runtime.production.min.js".

### ISSUE THREAD

**Issue by dastuer** [MMF-FE/vite-plugin-cdn-import#43]
Build failed in 9.67s
error during build:
RollupError: node_modules/react/cjs/react-jsx-runtime.production.min.js (12:7): "default" is not exported by "react?commonjs-external", imported by "node_modules/react/cjs/react-jsx-runtime.production.min.js".
file: G:/WorkSpace/WebStormProjects/react-learn-2024/day-06/rt-jk/node_modules/react/cjs/react-jsx-runtime.production.min.js:12:7
10: import * as commonjsHelpers from "commonjsHelpers.js";
11: import { __exports as reactJsxRuntime_production_min } from "\u0000G:/WorkSpace/WebStormProjects/react-learn-2024/day...
12: import require$$0 from "\u0000react?commonjs-external";
           ^
13:
14: 'use strict';var f=require$$0,k=Symbol.for("react.element"),l=Symbol.for("react.fragment"),m=Object.prototype.hasOwnP...
    at getRollupError (file:///G:/WorkSpace/WebStormProjects/react-learn-2024/day-06/rt-jk/node_modules/rollup/dist/es/shared/parseAst.js:394:41)
    at error (file:///G:/WorkSpace/WebStormProjects/react-learn-2024/day-06/rt-jk/node_modules/rollup/dist/es/shared/parseAst.js:390:42)
    at Module.error (file:///G:/WorkSpace/WebStormProjects/react-learn-2024/day-06/rt-jk/node_modules/rollup/dist/es/shared/node-entry.js:13896:16)
    at Module.traceVariable (file:///G:/WorkSpace/WebStormProjects/react-learn-2024/day-06/rt-jk/node_modules/rollup/dist/es/shared/node-entry.js:14344:29)
    at ModuleScope.findVariable (file:///G:/WorkSpace/WebStormProjects/react-learn-2024/day-06/rt-jk/node_modules/rollup/dist/es/shared/node-entry.js:12025:39)
    at Identifier.bind (file:///G:/WorkSpace/WebStormProjects/react-learn-2024/day-06/rt-jk/node_modules/rollup/dist/es/shared/node-entry.js:7382:40)
    at VariableDeclarator.bind (file:///G:/WorkSpace/WebStormProjects/react-learn-2024/day-06/rt-jk/node_modules/rollup/dist/es/shared/node-entry.js:4776:23)
    at VariableDeclaration.bind (file:///G:/WorkSpace/WebStormProjects/react-learn-2024/day-06/rt-jk/node_modules/rollup/dist/es/shared/node-entry.js:4772:28)
    at Program.bind (file:///G:/WorkSpace/WebStormProjects/react-learn-2024/day-06/rt-jk/node_modules/rollup/dist/es/shared/node-entry.js:4772:28)
    at Module.bindReferences (file:///G:/WorkSpace/WebStormProjects/react-learn-2024/day-06/rt-jk/node_modules/rollup/dist/es/shared/node-entry.js:13877:18)
`

**Comment by dastuer** [comment]
vite.config.js
```
import {defineConfig} from 'vite'
import react from '@vitejs/plugin-react'
import * as path from "node:path";
import {visualizer} from "rollup-plugin-visualizer";
import  {autoComplete, Plugin as importToCDN} from 'vite-plugin-cdn-import'
// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react(),
    visualizer({open: true}),
    importToCDN({
      modules: [
        autoComplete('react'),
        autoComplete('react-dom')
      ],
    }),
  ],
  resolve: {
    alias: {
      '@': path.resolve(__dirname, 'src'),
    }
  },
  build: {
    sourcemap: true
  }
})
```

**Comment by dastuer** [comment]
package.json
```
{
  "name": "rt-jk",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "lint": "eslint . --ext js,jsx --report-unused-disable-directives --max-warnings 0",
    "preview": "vite preview",
    "analyze": "source-map-explorer 'dist/assets/*.js'"
  },
  "dependencies": {
    "@ant-design/icons": "^5.3.6",
    "@reduxjs/toolkit": "^2.2.3",
    "antd": "^5.16.2",
    "axios": "^1.6.8",
    "dayjs": "^1.11.10",
    "echarts": "^5.5.0",
    "normalize.css": "^8.0.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-quill": "2.0.0",
    "react-redux": "^9.1.1",
    "react-router-dom": "^6.22.3"
  },
  "devDependencies": {
    "@types/react": "^18.2.66",
    "@types/react-dom": "^18.2.22",
    "@vitejs/plugin-react": "^4.2.1",
    "rollup-plugin-visualizer": "^5.12.0",
    "sass": "^1.75.0",
    "vite": "^5.2.0",
    "vite-plugin-cdn-import": "^0.3.5"
  }
}
```

**Comment by Allenice** [comment]
请使用最新的 1.x 版本
